version: "3.3"

services:
        influx:
                image: influxdb:2.1
                volumes:
                        - db-data:/var/lib/influxdb2
                ports:
                        - "8086:8086"
                restart: unless-stopped
        inverter_read:
                build: inverter
                depends_on:
                        - influx
                devices:
                        - "/dev/ttyUSB0:/dev/ttyUSB0"
                restart: unless-stopped
                env_file:
                        - solarpi.env
volumes:
        db-data:
