version: "3.3"

services:
        influx:
                image: influxdb:2.1
                volumes:
                        - db-data:/var/lib/influxdb2
                        - type: bind
                          source: $PWD/docker/influxdb/config.yml
                          target: /etc/influxdb2/config.yml
                ports:
                        - "80:80"
                restart: always
        combined_read:
                build: combined
                depends_on:
                        - influx
                devices:
                        - "/dev/ttyUSB0:/dev/ttyUSB0"
                restart: always
                env_file:
                        - solarpi.env
volumes:
        db-data:
