version: "3.9"

services:
        sdm_read:
                build: sdm
                #depends_on:
                #        - influx
                #devices:
                #        - "/dev/ttyUSB0:/dev/ttyUSB0"
                restart: unless-stopped
                env_file: 
                        - solarpi.env
volumes:
    db-data:

