version: "3.9"

services:
        influx:
                image: influxdb:2.0.8
                volumes:
                        - db-data:/var/influxdb
                ports:
                        - "8086:8086"
                restart: unless-stopped
volumes:
    db-data:

