version: "3.3"

services:
        influx:
                image: influxdb:2.1
                volumes:
                        - test-db-data:/var/lib/influxdb2
                ports:
                        - "8086:8086"
                restart: unless-stopped
        sdm_read:
                build: sdm
                depends_on:
                        - influx
                #devices:
                #        - "/dev/ttyUSB0:/dev/ttyUSB0"
                restart: unless-stopped
                stdin_open: true # docker run -i
                tty: true
                env_file:
                        - solarpi.env
volumes:
        test-db-data:
