version: "3.9"

services:
        influx:
                image: influxdb:2.0.8
                volumes:
                        - test-db-data:/var/influxdb
                ports:
                        - "8086:8086"
                restart: unless-stopped
        sdm_read:
                build: sdm
                depends_on:
                        - influx
                #devices:
                #        - "/dev/ttyUSB0:/dev/ttyUSB0"
                restart: unless-stopped
                env_file: 
                        - solarpi.env
volumes:
    test-db-data:

